artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source: https://drive.google.com/uc?id=1pNuyMlW0FkbP-0C08RE5MePLY6YbUxBo
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion